name: verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: setup-go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: 'stable'

      - name: setup-osquery
        run: |
         curl -LO https://pkg.osquery.io/deb/osquery_5.11.0-1.linux_amd64.deb
         sudo dpkg -i osquery_5.11.0-1.linux_amd64.deb

      - name: verify
        run: make verify-ci

